### ISSUE TITLE
Relationships references is wrong

### ISSUE THREAD

**Issue by jlcarvalho** [daliwali/fortune-mongodb#10]
The relationships references are wrong in this adapter and returns something like https://gist.github.com/jlcarvalho/bca2502ba26691cb03a7.

The attributes `self` and `related` outputs garbage.

**Comment by daliwali** [comment]
Oops, this is indeed a bug. Will fix.

**Comment by daliwali** [comment]
Fixed in this commit https://github.com/daliwali/fortune-mongodb/commit/333139076a434fa70cf0ba5570cba5fc24668622.
